### PR TITLE
fix: paste at active cursor location instead of at marker location

### LINKED ISSUE #165: Paste at active cursor location
Currently paste puts the block at the marker location (if any) and onto the workspace otherwise. It should put the block at the cursor location instead of the marker location, so that the user does not need to explicitly create a marker.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Fixes #165 

If the cursor location is not valid, pastes on the workspace (same behaviour as before).

The first commit cleans up a helper function to refer to "nodes" instead of "marker" and "cursor". The second commit actually changes the behaviour.

### CODE REVIEW

File: src/navigation.ts [hunk 1]
```diff
@@ -687,57 +687,54 @@ export class Navigation {
...
     workspace: Blockly.WorkspaceSvg,
-    markerNode: Blockly.ASTNode,
-    cursorNode: Blockly.ASTNode,
+    firstNode: Blockly.ASTNode,
+    secondNode: Blockly.ASTNode,
   ): boolean {
-    if (!this.logConnectionWarning(markerNode, cursorNode)) {
+    if (!this.logConnectionWarning(firstNode, secondNode)) {
       return false;
     }
```
Comment (cpcallen) [inline src/navigation.ts]:
```suggestion
    if (!this.logConnectionWarning(firstNode, secondNode)) return false;
```

File: src/navigation.ts [hunk 2]
```diff
@@ -1343,9 +1340,9 @@ export class Navigation {
     block: Blockly.BlockSvg,
   ): boolean {
     let isHandled = false;
-    const markedNode = workspace.getMarker(this.MARKER_NAME)?.getCurNode();
+    const markedNode = workspace.getCursor()?.getCurNode();
```
Comment (cpcallen) [inline src/navigation.ts]: Maybe `cursorNode` or `focusedNode` instead of `markedNode`?

File: src/navigation.ts [hunk 3]
```diff
@@ -687,57 +687,54 @@ export class Navigation {
...
   /**
-   * Tries to connect the given marker and cursor node.
+   * Tries to intelligently connect the blocks or connections
+   * represented by the given nodes, based on node types and locations.
    *
    * @param workspace The main workspace.
-   * @param markerNode The node to try to connect to.
-   * @param cursorNode The node to connect to the markerNode.
+   * @param firstNode The first node to connect.
+   * @param secondNode The second node to connect.
```
Comment (cpcallen) [inline src/navigation.ts]: If I understand correctly `secondNode` is the thing being attached, and `firstNode` is the location to attach it to.  Perhaps `newLocation` and `newItem`, or `parent` and `child`, or similar (instead of `first` and `second`)?

**Review by cpcallen — COMMENTED** [review]
I think the actual implementation of `tryToConnectNodes` should be revised so that it has the same behaviour regardless of whether `firstNode` is a block or that block's parent connection—but I think that can be done in a later PR, especially as this is a good, straightforward refactor.

File: src/navigation.ts (hunk 2 above)
Comment (rachel-fenichel) [reply src/navigation.ts]: Renamed to `targetNode`.

File: src/navigation.ts (hunk 3 above)
Comment (rachel-fenichel) [reply src/navigation.ts]: Will that still apply if this function is made to actually be properly symmetrical, though?

Comment (cpcallen) [reply src/navigation.ts]: Hmm.  I agree that my proposed change would be silly if the function was commutative—but I am not sure I understand why we would want that.

~~When moving blocks (or adding new blocks from the toolbox), there is always one group of blocks (the one that is moving / new)that's being connected by its root (prev/output) connection, and one group of blocks that is being connected by a child (next/input) connection.~~

Oh, scratch that (no pun intended): I've been spending too much time looking at event-driven code, because I'd forgotten you can connect blocks to the top of a stack as well as the bottom, and to the output of a top-level value block.  So the parent/child naming scheme might not be sensible—but is a moving blocks vs. stationary blocks distinction also not still useful?  Hmm.  🤔

Let's chat about this tomorrow.  I want to understand why you would like to make this function symmetric.

Comment (rachel-fenichel) [reply src/navigation.ts]: Updated to change names. PTAL.

**Review by cpcallen — APPROVED** [review]
