### PR TITLE
fix: scroll into view used the wrong position

### LINKED ISSUE #577: Scroll block away from view when inserting a block
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

When the project is long (blocks are far apart vertically), inserting a new block to the bottom of the block stack seems to scroll the newly-added block away from view. The expected behaviour is for the newly-added block to be in view after insertion.

### Reproduction steps

1. Drag the "draw" block to away from the "setup" block so that it is at the bottom of the screen.
2. Press "T" to open toolbox.
3. Navigate to a block in the flyout.
4. Hit "ENTER" on a block to insert.
5. See the newly added block be in move mode and out of view.

Moving the newly-added block around, or confirming move then navigating around with arrow keys moves focused block correctly back into view

### Stack trace

```shell

```

### Screenshots

**Video of reproduction**
https://github.com/user-attachments/assets/3ffe2822-2817-49c9-9214-ce24aad1babe

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
It used the position from positionNewTopLevelBlock, not the initial insert
position. Delay the setting of current node until the position is correct.

Fixes #577

### CODE REVIEW

File: src/actions/enter.ts [hunk 1]
```diff
@@ -146,8 +146,6 @@ export class EnterAction {
 
     workspace.setResizesEnabled(true);
 
-    getFocusManager().focusTree(workspace);
```
Comment (microbit-matt-hillsdon) [inline src/actions/enter.ts:149]: This line was pointless since `setCurNode` started moving focus.

**Review by gonfunko — APPROVED** [review]
