### PR TITLE
fix: Fix when the context menu is allowed to open

### LINKED ISSUE #276: Context menu should work via keyboard in the flyout
The context menu should work via keyboard in the flyout in the same way as in the regular workspace (some actions may have different enablement, but it should be possible to trigger the menu).

At the moment if you trigger by mouse you get Help and Cut/Copy/Paste. It unhelpfully closes the flyout due to #200 but the menu does work.

MakeCode has additional context menu entries for variables:

Image

### LINKED ISSUE #434: Can trigger context menu in keyboard move mode
You can trigger the context menu via e.g. Cmd+Enter in move mode (but not right-click).

This seems inadvisable in and of itself and likely any mutations you can trigger from the menu are buggy.

### PR DESCRIPTION
**Pull request by RoboErikG**
Fixes #434 
Fixes #276

#546 is partly fixed by this change but may still need some work for shortcuts other than menu opening.

This fixes the precondition checks for showing the action menu and also enables the action menu to be shown in the flyout so that it's consistent with right click.

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Assigning @BenHenning to review because I don't understand the workspace state changes.

**Comment by rachel-fenichel** [comment]
Also fixes (?) https://github.com/google/blockly-keyboard-experimentation/issues/276

**Comment by RoboErikG** [comment]
It partly fixes 276 by allowing the context menu to open in the flyout, but making copy/paste work correctly requires fixing some things in core or undoing Maribeth's change to depend on the core callbacks.

**Comment by RoboErikG** [comment]
I mixed up bugs, this does fix #276 and partially fixes #546. Updated the description to match.

**Review by BenHenning — COMMENTED** [review]
Thanks @RoboErikG. I think the solution makes sense. Is it possible add tests for these cases?

File: test/webdriverio/test/test_setup.ts [hunk 1]
```diff
@@ -431,3 +431,40 @@ export async function isDragging(
...
+    }
+    const actionItem = Blockly.ShortcutRegistry.registry.getRegistry()[action];
+    if (!actionItem || !actionItem.preconditionFn) {
+      throw new Error(
+        `No registered action or missing precondition: ${action}`,
+      );
+    }
+    return actionItem.preconditionFn(workspace, {
+      focusedNode:
+        Blockly.FocusManager.getFocusManager().getFocusedNode() ?? undefined,
```
Comment (BenHenning) [inline test/webdriverio/test/test_setup.ts]: Can `node` from above be reused here? I think technically it's guaranteed to be defined at this point, too, but you could always amend the conditional on line 456 to check for node's truthiness to placate the compiler (if needed).

File: test/webdriverio/test/actions_test.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    // Navigate to draw_circle_1.
+    await tabNavigateToWorkspace(this.browser);
+    await setCurrentCursorNodeById(this.browser, 'draw_circle_1');
+    // Navigate to a toolbox category
+    await moveToToolboxCategory(this.browser, 'Functions');
+    // Move to flyout.
+    await this.browser.keys(Key.ArrowRight);
+
+    chai.assert.isTrue(
+      await checkActionPrecondition(this.browser, 'menu'),
```
Comment (BenHenning) [inline test/webdriverio/test/actions_test.ts]: Is it possible to actually open the menu and verify that it's open rather than checking the precondition? That would be a lot closer to what the user experiences (and thus perhaps a bit more robust against implementation changes and refactors that don't change the end user behavior).

**Review by BenHenning — APPROVED** [review]
Thanks @RoboErikG! Approving to unblock, but I did have some thoughts on the tests. Feel free to re-add me if you'd like another review pass.
