### PR TITLE
fix(mover): Pass drag delta to `dragger.onDrag` in pixels

### LINKED ISSUE #446: Constrained move after unconstrained move translates the block in MakeCode
This issue only occurs in MakeCode, and not the blockly-keyboard-experimentation test page.

Reproduction:
- Insert a top-level block without any constrained positions
- Move the block using unconstrained move (modifier key and arrows)
- Attempt to the move the block using constrained move (arrows only)
- The block unexpectedly moves in the same direction you previously moved the block in unconstrained move mode
- The amount the block moves increases on each subsequent arrow key press

Please see screen capture below:
Image

What is happening:
The `newLoc` passed to the overridden `drag` method is being unexpectedly updated during constrained moves after an unconstrained move has occurred. This then calls `drag.super` and in turn `this.block.moveDuringDrag` which actually translates the block. It is unclear why there is a difference in behaviour between MakeCode and the test page.

A potential fix:
This can be fixed by removing the call to `info.updateTotalDelta()` inside the `moveConstrained` method, however, the consequences of doing this are not fully understood by us and we want to avoid any negative side effects.

### PR DESCRIPTION
**Pull request by cpcallen**
There was an error in the initial implementation of `DragMover` (in PR #317), where the drag delta was being passed in workspace coordinates instead of pixels.  This lead to various problems, notably #446.

Fixes #446.

### CODE REVIEW

File: src/actions/mover.ts [hunk 1]
```diff
@@ -302,7 +302,7 @@ export class Mover {
 
     info.dragger.onDrag(
       info.fakePointerEvent('pointermove', direction),
-      info.totalDelta,
+      info.totalDelta.clone().scale(workspace.scale),
```
Comment (BenHenning) [inline src/actions/mover.ts:305]: This makes me wonder if we should have distinct types for different coordinate spaces, e.g. ScreenCoordinate and WorkspaceCoordinate. It's not obvious from code that scaling performs the space conversion, or what coordinate system we're currently in at this point (since if `totalDelta` is already in screen space then scaling again would be wrong).

File: test/webdriverio/test/move_test.ts [hunk 2]
```diff
@@ -13,6 +13,9 @@ import {
   tabNavigateToWorkspace,
   testFileLocations,
   testSetup,
+  sendKeyAndWait,
+  keyDown,
+  keyRight,
```
Comment (BenHenning) [inline test/webdriverio/test/move_test.ts]: Looks like this can be removed.

File: test/webdriverio/test/move_test.ts [hunk 3]
```diff
@@ -218,3 +277,22 @@ function getConnectedBlockInfo(browser: Browser, id: string, index: number) {
     index,
   );
 }
+
+/**
+ * Given a block ID, get the coordinates of that block, as returned by
+ * .getRelativeTosSurfaceXY().
```
Comment (BenHenning) [inline test/webdriverio/test/move_test.ts]:
```suggestion
 * getRelativeToSurfaceXY().
```

Nit: typo fix, plus removed the '.' since it doesn't seem necessary for the code reference.

File: test/webdriverio/test/move_test.ts [hunk 4]
```diff
@@ -145,6 +148,62 @@ suite('Move tests', function () {
       await this.browser.keys(Key.Escape);
     }
   });
+
+  // When a top-level block with no previous, next or output
+  // connections is subject to a constrained move, it should not move.
+  //
+  // This includes a regression test for issue #446 (fixed in PR #599)
+  // where, due to an implementation error in Mover, constrained
+  // movement following unconstrained movement it would result in the
```
Comment (BenHenning) [inline test/webdriverio/test/move_test.ts]:
```suggestion
  // movement following unconstrained movement would result in the
```

Extra 'it' if I'm reading this correctly.

File: test/webdriverio/test/move_test.ts [hunk 5]
```diff
@@ -145,6 +148,62 @@ suite('Move tests', function () {
...
+  // block unexpectedly moving (unless workspace scale was === 1)
```
Comment (BenHenning) [inline test/webdriverio/test/move_test.ts]:
```suggestion
  // block unexpectedly moving (unless workspace scale was === 1).
```

Super nit on punctuation for consistency.

**Review by BenHenning — APPROVED** [review]
Thanks @cpcallen! Seems like a really nice fix. Just had some nits and one core design consideration, but otherwise the PR LGTM.

File: src/actions/mover.ts (hunk 1 above)
Comment (cpcallen) [reply src/actions/mover.ts:305]: This would be a great idea; I've filed google/blockly#9156 for future consideration.

Relatedly, one of the things I somewhat dislike about TypeScript (and also Go) is duck typing: it should be possible to give different names to the same type specification and have the compiler flag any mixed use (absent explicit casts).  For object types it's pretty easy to make things different shapes (adding a dummy method to the class definition changes the type without changing the actuals shape of the objects in memory), but a classic use of nominal typing is to distinguish between `string`s containing HTML and ones containing plain text, and enforce calling a function to do escaping when converting the latter to the former.  TypeScript doesn't let you do that—you'd have to use subclasses of the `String` object type rather than plain `string`s.

File: test/webdriverio/test/move_test.ts (hunk 4 above)
Comment (cpcallen) [reply test/webdriverio/test/move_test.ts]: Good spot.  This comment got reworded several times to try to keep it to a reasonable length; looks like I can shorten it by one more word!
