### PR TITLE
fix: change cursor rendering for empty value inputs in zelos

### LINKED ISSUE #288: Replace tiny circle cursor with outline for a value input with no shadow block (e.g. if)
In Zelos at least, we think the cursor should outline the space where the block would go.

So instead of this:

Image

...do this (but without the hand-drawn vibe):

Image

### PR DESCRIPTION
**Pull request by rachel-fenichel**
This fixes #288 but only for zelos. Falls back on old behaviour for zelos.

### CODE REVIEW

File: src/line_cursor.ts [hunk 1]
```diff
@@ -702,27 +702,89 @@ export class LineCursor extends Marker {
...
+   * Check whether the node represents a value input connection.
+   *
+   * @param node The node to check
+   * @returns True if the node represents a value input connection.
+   */
+  private isValueInputConnection(node: ASTNode) {
+    if (!node) return false;
+    if (node.getType() != ASTNode.types.INPUT) {
+      return false;
+    }
```
Comment (cpcallen) [inline src/line_cursor.ts]: Even by your rules this can be simplified:  😉
```suggestion
    if (node?.getType() !== ASTNode.types.INPUT) return false;
```
(Though it may not be immediately obvious that `node?.getType()` evaluates to `undefined` if `node` is null or undefined, and `undefined !== INPUT` evaluates to true.)

File: src/line_cursor.ts [hunk 2]
```diff
@@ -702,27 +702,89 @@ export class LineCursor extends Marker {
...
+    const connection = node.getLocation() as Blockly.Connection;
+    return connection.type == Blockly.ConnectionType.INPUT_VALUE;
```
Comment (cpcallen) [inline src/line_cursor.ts]:
```suggestion
    return connection.type === Blockly.ConnectionType.INPUT_VALUE;
```

File: src/line_cursor.ts [hunk 3]
```diff
@@ -702,27 +702,89 @@ export class LineCursor extends Marker {
...
-    if (!block.isShadow()) {
-      Blockly.common.setSelected(block);
-    } else {
-      block.addSelect();
+
+    if (this.isValueInputConnection(curNode)) {
+      this.showAtInput(curNode);
+    }
+
+    if (curNodeType == ASTNode.types.BLOCK) {
```
Comment (cpcallen) [inline src/line_cursor.ts]:
```suggestion
    } else if (curNodeType === ASTNode.types.BLOCK) {
```

**Comment by rachel-fenichel** [comment]
@gonfunko PTAL

**Review by gonfunko — APPROVED** [review]
