### PR TITLE
fix: Scroll flyout contents into bounds.

### LINKED ISSUE #90: Scroll toolbox flyout to follow cursor
When there are too many blocks in the flyout and you select a block at beyond the screen, the scroll bar will not scroll down automatically and you must use the mouse to scroll down.

```js
const flyout=workspace.getFlyout();
const cursor = flyout ? flyout.getWorkspace().getCursor() : null;
const drawer = cursor.getDrawer();
const blockSvg = drawer ? drawer.getSvgRoot() : null;
blockSvg.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'start' });
```

I tried to use the above code to solve it, but unfortunately it didn't work.

### LINKED ISSUE #150: Error to console when handling enter on a label in a flyout
If you add content of kind=label to a toolbox category then the keyboard navigation will visit it and pressing enter on it will cause an error on the console.

```
bundle.js:2 Uncaught Error: No callback function found for flyout button.
    at Ht.triggerButtonCallback (bundle.js:2:1888927)
    at Object.callback (bundle.js:2:1899298)
    at Fp.onKeyDown (bundle.js:2:1476389)
    at ai (bundle.js:2:1142398)
    at HTMLDocument.s (bundle.js:2:1068151)
```

There's an example label [in the subcategory on this deployment](https://category-toolbox.blockly-keyboard-experimentation.pages.dev/).

Image

I think the typescript type might be missing the kind=label case.

MakeCode uses labels as headings and subheadings in its toolbox flyouts.

### PR DESCRIPTION
**Pull request by gonfunko**
This PR fixes #90 by updating the flyout to scroll the selected item into view. It refactors similar logic for the main workspace out into a shared function used by both. It also fixes #150.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
It would be great to support labels/buttons too as this can feel quite broken with MakeCode's label use for headings and flyout sections.

They don't seem to have `getBoundingRectangle` but perhaps it would be easy to add. If not it seems to work with this (I've added one for an example below, you'll have to make a very short browser window though).

[Code also here](https://github.com/google/blockly-keyboard-experimentation/compare/flyout-scroll...microbit-matt-hillsdon:blockly-keyboard-experimentation:label-flyout-scroll) and [deployed here](https://label-flyout-scroll.blockly-keyboard-experimentation.pages.dev/).

```patch
diff --git a/src/flyout_cursor.ts b/src/flyout_cursor.ts
index fcb134c..84eefb5 100644
--- a/src/flyout_cursor.ts
+++ b/src/flyout_cursor.ts
@@ -85,15 +85,21 @@ export class FlyoutCursor extends Blockly.Cursor {
     super.setCurNode(node);
 
     const location = node.getLocation();
+    let bounds: Blockly.utils.Rect | undefined;
     if (
-      !(
-        'getBoundingRectangle' in location &&
-        typeof location.getBoundingRectangle === 'function'
-      )
-    )
-      return;
-
-    const bounds = location.getBoundingRectangle();
+      'getBoundingRectangle' in location &&
+      typeof location.getBoundingRectangle === 'function'
+    ) {
+      bounds = location.getBoundingRectangle();
+    } else if (location instanceof Blockly.FlyoutButton) {
+      const {x, y} = location.getPosition();
+      bounds = new Blockly.utils.Rect(
+        y,
+        y + location.height,
+        x,
+        x + location.width,
+      );
+    }
     if (!(bounds instanceof Blockly.utils.Rect)) return;
 
     scrollBoundsIntoView(bounds, this.flyout.getWorkspace());
diff --git a/test/blocks/toolbox.js b/test/blocks/toolbox.js
index a402ae7..125b755 100644
--- a/test/blocks/toolbox.js
+++ b/test/blocks/toolbox.js
@@ -35,6 +35,10 @@ export const p5CategoryContents = [
       },
     },
   },
+  {
+    kind: 'label',
+    text: "Writing text"
+  },
   {
     kind: 'block',
     type: 'write_text_with_shadow',
```

**Comment by microbit-matt-hillsdon** [comment]
[Screen recording of the MakeCode flyout so you can see my motivation for adding label support](https://github.com/user-attachments/assets/4bbedd22-5aea-4c43-87b1-5271b8a933da).

**Comment by gonfunko** [comment]
Ah, they already have that method in Blockly v12 and I was referencing that branch and thought they'd be covered, but it's new in v12. There's a lot of flyout changes in that version (you can now add arbitrary types of elements to the flyout), but the API contract requires getBoundingRectangle(), so the good news is this should work well going forward. That said, I'll go ahead and patch in your changes momentarily to unblock things now; thank you!

File: src/navigation.ts [hunk 1]
```diff
@@ -1452,7 +1454,7 @@ export class Navigation {
     );
     if (typeof buttonCallback === 'function') {
       buttonCallback(button);
-    } else {
+    } else if (!button.isLabel()) {
```
Comment (microbit-matt-hillsdon) [inline src/navigation.ts:1457]: ❤️

I think this is a fix for #150

File: src/workspace_utilities.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+  workspace: Blockly.WorkspaceSvg,
+) {
+  const scale = workspace.getScale();
+
+  // Add some padding to the bounds so the element is scrolled comfortably
+  // into view.
+  bounds.top -= 10;
+  bounds.bottom += 10;
+  bounds.left -= 10;
+  bounds.right += 10;
```
Comment (BenHenning) [inline src/workspace_utilities.ts:32]: Should we be making a copy of the `Rect` here? Unsure of the implications of changing the bounding rect returned from the block.

**Review by BenHenning — APPROVED** [review]
Thanks @gonfunko! Wondering if #150 should be marked as fixed here, too, per @microbit-matt-hillsdon's comment.

Otherwise had one comment, but approving to unblock.

File: src/workspace_utilities.ts (hunk 2 above)
Comment (gonfunko) [reply src/workspace_utilities.ts:32]: Yeah that's a good call, done.
